POST http://localhost:3003/bikes/cadastro
Content-Type: application/json

{
    "color": "Preto",
    "brand": "GTS",
    "gear_speed": 21,
    "model": "Force",
    "price": 4530
}

###
DELETE http://localhost:3003/bikes/fc95c3f6-5a03-47a2-83b5-e4ed591af8e5

###
PUT http://localhost:3003/bikes/detalhes/ddb351e4-ef5f-4a29-8e46-842e02cbab35
Content-Type: application/json

{
    "price": 1400
}

###
GET http://localhost:3003/bikes

###
GET http://localhost:3003/bikes/rosa

###
GET http://localhost:3003/bikes/valores/crescente